context:
  version: "2026.07"

package:
  name: gen3-client
  version: ${{ version }}

source:
  url: https://github.com/uc-cdis/cdis-data-client/archive/${{ version }}.tar.gz
  sha256: 0726d7b639fd727f6e71d04b1fd6c955dd43f858d403fd5befc92cdb496cde27

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gen3-client --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Data access client for Gen3 data commons
  homepage: https://github.com/uc-cdis/cdis-data-client
  repository: https://github.com/uc-cdis/cdis-data-client

extra:
  recipe-maintainers:
    - danielnachun
