context:
  version: "2026.04"

package:
  name: gen3-client
  version: ${{ version }}

source:
  url: https://github.com/uc-cdis/cdis-data-client/archive/${{ version }}.tar.gz
  sha256: 32f220d82b69c37bb14d1bef305bc322a7a0037aab9085991d42905fa404e002

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gen3-client --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Data access client for Gen3 data commons
  homepage: https://github.com/uc-cdis/cdis-data-client
  repository: https://github.com/uc-cdis/cdis-data-client

extra:
  recipe-maintainers:
    - danielnachun
