context:
  version: "2026.09"

package:
  name: gen3-client
  version: ${{ version }}

source:
  url: https://github.com/uc-cdis/cdis-data-client/archive/${{ version }}.tar.gz
  sha256: 5e3cc34d98c58b3150b3e55569cc7353038398496854933631be5c1e1ac2d54e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gen3-client --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Data access client for Gen3 data commons
  homepage: https://github.com/uc-cdis/cdis-data-client
  repository: https://github.com/uc-cdis/cdis-data-client

extra:
  recipe-maintainers:
    - danielnachun
