context:
  version: "2025.11"

package:
  name: gen3-client
  version: ${{ version }}

source:
  url: https://github.com/uc-cdis/cdis-data-client/archive/${{ version }}.tar.gz
  sha256: 3b0035c07ae580071ae45b843649344257cf4a4b5b6ecb0a57a5d1fbf209c7f0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gen3-client --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Data access client for Gen3 data commons
  homepage: https://github.com/uc-cdis/cdis-data-client
  repository: https://github.com/uc-cdis/cdis-data-client

extra:
  recipe-maintainers:
    - danielnachun
