context:
  version: "2025.12"

package:
  name: gen3-client
  version: ${{ version }}

source:
  url: https://github.com/uc-cdis/cdis-data-client/archive/${{ version }}.tar.gz
  sha256: 5c9446a9b54ad48ce1f7efb31317bc5602bc6dac61bf980609650b2a4d53fa78

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gen3-client --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Data access client for Gen3 data commons
  homepage: https://github.com/uc-cdis/cdis-data-client
  repository: https://github.com/uc-cdis/cdis-data-client

extra:
  recipe-maintainers:
    - danielnachun
